# Generated by Django 5.1.2 on 2024-10-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_news_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('PU', 'Published'), ('AR', 'Archived')], default='DR', max_length=20),
        ),
    ]
